### ISSUE TITLE
Your S3 Keys are sitting in this repo

### ISSUE THREAD

**Issue by mreider** [cloudfoundry-community/redis-boshrelease#16]
Suggest you remove...

**Comment by drnic** [comment]
@mreider fortunately they are read-only keys - back in the day when I started with bosh I cargo culted the BOSH team examples for using encryption keys & access keys for blobstores. Only last year did I learn how to setup an AWS bucket to be publicly readable; so fortunately now `bosh-gen new` will automatically create S3 buckets that "just work". Unfortunately, I don't know how to fix my current buckets and remove the read-only S3 keys. Ideas?

**Comment by drnic** [comment]
This was all happily cleaned up, keys rotated, etc.
