### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SamuelMarks** [cloudfoundry-community/redis-boshrelease#20]
> One of the fastest ways to get redis running on any infrastructure is too deploy this bosh release

Should be:

One of the fastest ways to get redis running on any infrastructure is **to** deploy this bosh release

**Comment by thewoolleyman** [comment]
Lol, almost a year and a half and still not fixed.  How many OCD people has that annoyed...

**Comment by dennisjbell** [comment]
Odd, this was fixed in commit  d4147682d2fa327c756222f2e6a224294e901ef3 on November 5th, 2013, before this issue was raised.  Either way, closing now.

**Comment by thewoolleyman** [comment]
@dennisjbell No, this is about the Repo description field, not anything committed (click "edit" at the top of the repo page on github)

**Comment by dennisjbell** [comment]
Ah, that clears that up -- couldn't tell that from the original description, because that WAS an actual issue in the README.md file long before.  Solved!
