### ISSUE TITLE
Deploying the cf-redis-broker.

### ISSUE THREAD

**Issue by Alex-Mussell** [cloudfoundry-community/redis-boshrelease#46]
I have redis running in our environment, however there is no broker job unlike the pivotal redis release. What is the best way to expose Redis within my CF marketplace? The cf-redis-broker is lacking in docs. Any advice would be appreciated.

**Comment by mymasse** [comment]
Wondering the same thing? We've been using the pivotal release but it lacks High availability.

**Comment by Alex-Mussell** [comment]
Not a direct answer, but we decided to not bother with the HA capabilities, as you shouldn't use redis for persistent data anyway. So instead of forking or working this out, we decided to expose 2 instances of redis in 2 AZ's and pushed the HA availability down stream. If app developers want it for whatever reason, they can write it into their application code. It has actually worked really well.
To clarify, we went the the pivitol/shared-redis-release and not this one.

**Comment by mymasse** [comment]
OK, I don't understand: 2 deployments and 2 brokers? or two instances in the same deployment, which one is used by the broker?

**Comment by Alex-Mussell** [comment]
https://github.com/pivotal-cf/shared-redis-release

The above release has a broker errand which you run via bosh to expose redis to the cf marketplace. It's a bit strange in that the broker-registrar errand doesn't spawn a vm, but runs as 'errand job' actually on the vm.

Yes, we have 2 redis deployments eg redis-az1, redis-az2. Both are their own deployments and therefore have their own brokers. So in the marketplace there are 2 services: redis-az1, redis-az2. The app developers can than choose to write "HA" capabilities into their app by writing to both queues and reading from one. If one node dies, they have a retry that reads the other.

The reason it has worked is that for small apps that dont NEED HA, the user only pays for the resources of 1 redis instance. If someone says they want the HA capabilites, they pay and we expose the second redis service to them in the marketplace of their organisation. It allows for a bit of flexibility. Yes it isn't pure HA, but it's close enough for us.
