### ISSUE TITLE
Release new version of redis.

### ISSUE THREAD

**Issue by IamBread** [cloudfoundry-community/redis-boshrelease#48]
Master branch contains [a commit](https://github.com/cloudfoundry-community/redis-boshrelease/commit/a300fe8caa8d17433690ceb307d1731517619416) that allows sentinel to re-use the password provided to Redis for communication with Redis password protected instances. While this is in the master branch,  there is no release with  the newest features. Do you plan to release a new version of the BOSH release? If not what are the plans for maintaining BOSH releases?

Regards.

**Comment by kiril-dayradzhiev** [comment]
Hi there,
Could you estimate by when the release will be ready, currently I rely on it to be done in a short term?

Regards,
Kiril

**Comment by drnic** [comment]
@kiril-dayradzhiev I'm having some issues with our CI. Hopefully I can get someone who sort me out from the team over the next 12 hours or so, then can get the CI pipeline back up and running (from which I can then cut a release).

**Comment by drnic** [comment]
https://github.com/cloudfoundry-community/redis-boshrelease/releases/tag/v15.3.4 has been cut

I'm now working on releasing the compiled version of the release

**Comment by drnic** [comment]
Closing now. Another release will come later today with bump to bpm.

**Comment by kiril-dayradzhiev** [comment]
Hi again,
Thanks a lot for the speed light response :)

Have a great week.
